### ISSUE TITLE
Cross blockchain contract execution system

### ISSUE THREAD

**Issue by majorshimo** [JoinColony/colonyHackathon#27]
### Colony Hackathon Submission

**Project Title**

---
My goal is to develop a smart contract system that can operate accross blockchains. Im positive that a project like this will reduce the effort needed to work accross blockchains (vs developing a standard) and can exponentialize adoption.

**Project Description**

**Project Repository**

Team Members:
Simon Romano: simonromano2007@gmail.com
**Team Members and Contact info**

**Comment by yutarond** [comment]
I’d like to know more details!

**Comment by jrmoreau** [comment]
Cool idea! Let us know if you have any questions getting going on this!

**Comment by majorshimo** [comment]
Hi!
Id love to share more about the project. Would you mind giving me a little
background on yourself so i can see how to structure the details?
Thanks for the interest,
Simon

**Comment by majorshimo** [comment]
Thank you!
I have a ton of questions, any way you could give me a but of background on
yourself so i can see what to ask ;)
Simon

**Comment by jrmoreau** [comment]
@majorshimo I am a development intern at Colony. So basically I am at your service you need anything to help your progress.

**Comment by gichiba** [comment]
Hey @majorshimo, are you still looking for teammates? have you started planning out your project?

**Comment by majorshimo** [comment]
Still looking for teammates in case youre interested!

**Comment by majorshimo** [comment]
Hi Trevor! Just replied to your other message, let me know what you
think/if you want to talk over skype.

**Comment by TrevorOakley** [comment]
I have no project so any ethereum related one is fine with me. I would
prefer to learn something.

My whatsapp is 44 745 298 6739. I do not really use skype anymore. I use
hangout too (trevoroakley200@gmail.com) is my email address.

Trevor

**Comment by jrmoreau** [comment]
Marking that you're looking for team members.

**Comment by TrevorOakley** [comment]
looking to join a team really.

**Comment by jrmoreau** [comment]
@TrevorOakley there are a few others marked as looking for team members in the issues. Let me know if you need any assistance getting placed. Also might make sense to post you're looking to join a team in the Gitter as well.

**Comment by jrmoreau** [comment]
@majorshimo it's ok - thanks for letting us know. If you feel you'll probably stop it might make sense to close the issue. Let us know if you think this seems reasonable.

**Comment by majorshimo** [comment]
Yeah, it might be for the best
