### ISSUE TITLE
As-Yet Undetermined Colony Hackathon Submission (AYUCHS)

### ISSUE THREAD

**Issue by m-roberts** [JoinColony/colonyHackathon#29]
### Colony Hackathon Submission

**As-Yet Undetermined Colony Hackathon Submission (AYUCHS)**

---

**Project Description**

We don't really know what this will be yet.

**Project Repository**

We will attach a link when there is something to see.

**Team Members and Contact info**

@m-roberts
@ItsChoudhry

We are open to accepting new team members/contributors.

No additional info to share at this time.

**Comment by jrmoreau** [comment]
Thanks for posting the issue @m-roberts and @ItsChoudhry. Don't hesitate to reach out if you have any questions!
