### ISSUE TITLE
eduColony

### ISSUE THREAD

**Issue by sogasg** [JoinColony/colonyHackathon#33]
### Colony Hackathon Submission

**Project Title**
eduColony

---

**Project Description**

Bringing people out of poverty by providing education to the people that today are unable to get it.

**Project Repository**

**Team Members and Contact info**

Asgeir - [GitHub](https://github.com/sogasg) - [Twitter](https://twitter.com/sogasg) - [Telegram](t.me/Cryptekno)

More team members are required in order to carry out the project. Please, join me 😃

**Comment by sogasg** [comment]
Many people in the world are not able to get a good education. Some of the reasons for this can be:
- it's too expensive,
- people need to make money for to survive,
- oppression,
- there might not be any good education available,
- disabilities,
- no jobs available in their location,
- and more.

We want to provide education to the people that today are unable to get it.

We want to do this by launching a nonprofit Colony. Where students can apply for being paid for there education. Both payment and certifications/reputation will be on the blockchain. Paid students will start with a low "salary" that will grow as they progress through the programs. Hopefully, we will also find a way for students to be anonymous if they need it for protection (girls taking education in a place where it's not allowed, etc.).

When a student has finished the education, they have certificates/reputation on the blockchain to prove their education, and it should be possible for them to work remotely in a Colony or other decentralized organization.

Who will pay for this?
The organization will rely on donations. All transactions will be public on the blockchain, and therefore donators will be able to see exactly how their funds are allocated. We could also pay out "karmaCoin" to donators (not transferable). Maybe it even will be possible for the donors to participate in the governance of the colony.


Challenges:
- prove that it was the student that completed the exams - we need some sort of validator
- verify that the student exists and does not create multiple "accounts".


Some thoughts of how Colony can be used for this
- The non-profit will be a Colony.
- One domain = one subject (math).
- One domain/subject can have many courses each earning skill for that subject.
- Each course can only be completed once.
- One task can be used for each course with the exam being the requirement for payment (skill and payment).

This is my vision everything is up for discussion and change :)
Is this a viable idea?
Is this a good use case for Colony?
And, does anybody want to work on this with me?

**Comment by gichiba** [comment]
I think this is *definitely* a viable idea, and a good use case for Colony. It's also wise that you're limiting the scope to math at the moment. It's a bit easier to quantify and grade fairly, in my experience (I'm a former teacher). 

One way to get started might be to think about how you'd want to structure tasks and payouts. Would a task be for a specific assignment, or for a larger collection of assignments? Another bit of food for thought is how you might store certificates. It'd be relatively easy to put them as just standalone documents on IPFS, which would fit well with a task's specificationHash data. 

A more pragmatic problem that I've thought about often is the 'on the ground' bit. How are the students going to manage their accounts and private keys? Should they, or would it be alright to extend lines of trust to a teacher or mentor nearby?

**Comment by jrmoreau** [comment]
Definitely a great idea. Let's try to get you some team mates for this.

**Comment by sogasg** [comment]
# More details
I have been thinking a little bit about this. This might not be as ambiguous as the first idea but seems more feasible for the hackathon.

Companies could offer a paid certified education in exchange for that the student will work for the company for an agreed upon amount of time afterward. The salary for the education and work will be decided upon in the initial contract.

This way the student will get certificates that later can be used to find other work.

The company will get a worker that knows exactly what they need and they will help somebody get a (better) education. This also may give the company the option to pay less for a unique skill. Let's say a blockchain developer takes 3x the salary of a JavaScript developer. Then the company could educate the JS developer, and they both be better off (cheaper work / good education for later).

The student will have an Ethereum address tied to the certificate and the agreed-upon work. So if the student completes the education and breaks the contract (dont do the work at the company), this will show up when the other company looks up the address credentials and work story. An education has little worth if the worker can't be trusted to do agreed work.

The Colony would, in this case, make money (for salaries, etc.) by that companies and educators would need to pay a percentage of their earnings/payment.

A third entity would be the educators offering programs for a price.

For this we would need:

- A colony for managing this system.

- GUI for companies where they would go through a wizard:
  1. browse and selecting courses
  2. setting payments on completion of the different courses
  3. setting the amount of time they want the student to work with them afterward.
  4. etc.

- GUI for companies to find already educated students.

- GUI for educators to create courses; exams, assignments, and certificates (course material, like books, lectures etc. could reside on another platform).
- GUI wizard for educators to list their courses.

- GUI for potential students to browse educations/positions.

This is not a perfect solution, but I think its a start and something that could be started during the hackathon (MVP).

**Comment by mibrkelly** [comment]
This sounds interesting to me. I've been a math professor and worked in ed-tech. Let me know if you are still looking for teammates.

**Comment by jrmoreau** [comment]
@sogasg other teams have created sub-Gitters for their teams - if you decide to do that maybe post here and then update on who your team consists of.

**Comment by sogasg** [comment]
Decided to go for https://github.com/JoinColony/colonyHackathon/issues/42 instead
