### ISSUE TITLE
TrueGift

### ISSUE THREAD

**Issue by KCWx9** [JoinColony/colonyHackathon#34]
### Colony Hackathon Submission

**Project Title**

TrueGift
---

**Project Description**

A collaboration platform for crowdsourcing solutions to 21st century challenges.

Decentralised operations based on location for the co-creation of unique products by upcycling unwanted / unused materials through crowdsourced donations of time and skill.

**Project Repository**

https://github.com/KCWx9/TrueGift_Colony

**Team Members and Contact info**

@KCWx9
@gkimbwala
@justpixel 
@vardhanapoorv 
@Wipakelly 

We have the right team for the hackathon.

You can find us here: https://gitter.im/TrueGift_Colony
More updates to follow.

**Comment by jrmoreau** [comment]
Awesome idea! Let me know if you need any support from Colony to get going.

**Comment by gkimbwala** [comment]
I really like this idea and I would love to work on this with you!

**Comment by justpixel** [comment]
If you are looking for a UI designer, I would like to contribute to this project.

**Comment by vardhanapoorv** [comment]
I like the idea and would like to be a part of it

**Comment by Wipakelly** [comment]
I'm very interested in this idea and would like to help out!
