### ISSUE TITLE
Blockgeeks coupon code not working

### ISSUE THREAD

**Issue by csajedi** [JoinColony/colonyHackathon#51]
### Colony Hackathon Submission

Hi, this is not a hackathon idea as much as an actual issue. I've tried to use my coupon code on blockgeeks, but they reject it. Can someone else confirm that the code from the hackathon signup email is still valid?

---

**Comment by gichiba** [comment]
Hey @csajedi -- yes, you can use it if you use this link: https://courses.blockgeeks.com/hackathon/
