### ISSUE TITLE
Long Term Jobs Market for Developing Countries

### ISSUE THREAD

**Issue by farahbrunache** [JoinColony/colonyHackathon#53]
### Colony Hackathon Submission

**Project Title**

Long Term Jobs Market for Developing Countries
---

**Project Description**

Travay [pronounced "try-vi"] is a community board for citizens of developing countries to post community tasks in their community, and through the completion of tasks, tokens acquired can be liquidated for economic mobility. Developing nations have a lack of jobs and chances for economic mobility. By incentivizing needed services that their government cannot provide (i.e. trash pickup, water delivery) we can promote civic engagement, and empower others to take action to solve issues in their communities.

**Project Repository**

https://github.com/farahbrunache/travay-colony-vuejs-dapp

**Team Members and Contact info**

Farah Brunache | Developer
Twitter @farahbrunache
Github @farahbrunache

Iain Barclay | Researcher
Github @iainbarclay
Twitter @iainbarclay

Emily Kuo | Researcher
Github @bubblenote

**Am I accepting team members?**

Yes. Would love to have a designer join! +1 If you are proficient in Sketch. Additional developers are welcome too.

My original plan was to use StandardBounties for this idea. But recently discovered Colony. My hope in participating in this hackathon is to learn how to use Colony and connect with like minded people!

**Comment by gichiba** [comment]
Cool! I'll keep an eye out for any designers in the Gitter for ya!

**Comment by farahbrunache** [comment]
For anyone still looking for a team, my project is still accepting.

Developers, designers or even if you would like to help refine the project more.

Here's a visual of what I am looking to accomplish:

![high-level-project-description](https://user-images.githubusercontent.com/16567092/41025007-c832db4c-693e-11e8-9172-49329a44f9b9.png)

**Comment by gichiba** [comment]
This is looking great!

**Comment by epocket** [comment]
Hi Farah - I'd love to help out if I can, but it would be product shaping/refinement rather than development or design I'm afraid, so let me know if that would be useful. I'm currently doing a research project on "crowdwork" and how blockchain could support it, so hopefully I can give you some helpful input from what I've learned so far. I have a good technical background, so can help with architecture, etc. if needed, just not able to offer any code at the moment - let me know, no offence if I'm not a good fit - and good luck!

**Comment by farahbrunache** [comment]
Any help is greatly appreciate! How do you want to communicate? A private Gitter group?
If so, I created a channel: https://gitter.im/travay-colony-hackathon-2018/Lobby#.

**Comment by farahbrunache** [comment]
@bubblenote adding you to this discussion thread. If you're up to it let me know and I'll add you to the repo and you, Iain and I can begin refining the project.

I have a vue.js scaffold up and going through the colonyJS docs.

**Comment by bubblenote** [comment]
Yes yes, would love to help out! My email is emmytennis23@gmail.com fyi!

**Comment by farahbrunache** [comment]
@bubblenote, great! I'll add you to the team and repo - but I need your real name first :). Please also let me know when you are free next: https://doodle.com/poll/z89s3fyuk5r7wd58. 

I am thinking we do a Zoom session where I share my screen. From there we can divide up the tasks and get going!

@epocket, please also complete the poll -- so we can schedule a time for a remote session: https://doodle.com/poll/z89s3fyuk5r7wd58.

**Comment by bubblenote** [comment]
@farahbrunache My real name is Emily and I just filled out the poll!

**Comment by farahbrunache** [comment]
Thank you! I added you to the repo. When working please create your own branch/es so we can coordinate pushing to the master branch.

In a few hours I will be back to working on it, I will clean up the master a bit. In the meantime, I didn't create the Doodle poll correctly. Here it is again: https://doodle.com/poll/uquis3gpisuz7prq. Sorry to do this to you, but please fill out again. The first poll I sent had the meeting from 8 am to 11 pm! Yikes, we don't need to have a meeting that long. The new link has a break down of an hour increment. Once Ian responds I'll send the Zoom link and I'll share my screen and we can get going!

**Comment by epocket** [comment]
I hope I did the survey right - can do Sunday evening UK time if that is ok, if not please go ahead and I'll catch up later!

**Comment by farahbrunache** [comment]
@bubblenote, are you ready to join the meeting? https://zoom.us/j/6938611688

**Comment by YalorMewn** [comment]
Hey @farahbrunache this is a really cool project, if you're interested in continuing development on this idea Giveth.io is hosting a hackathon [here](https://github.com/Blockternship/take-off) you should submit an issue !
