### ISSUE TITLE
Doggy

### ISSUE THREAD

**Issue by gjeanmart** [JoinColony/colonyHackathon#65]
### Colony Hackathon Submission
**Project Title**
Doggy

---

**Project Description**
TDB

**Project Repository**
TDB
**Team Members and Contact info**
Greg Jeanmart

**Comment by jrmoreau** [comment]
Thanks for starting your issue @gjeanmart. Let us know if you need any assistance getting started.

**Comment by gjeanmart** [comment]
Unfortunately, lack of time, I have to renounce to this hackaton with sadness :(
I wish to learn more about Colony usages in the future.
Best of luck !
