### ISSUE TITLE
Science articles publishing service

### ISSUE THREAD

**Issue by BukinPK** [JoinColony/colonyHackathon#81]
### Colony Hackathon Submission

**Project Title**
science articles publishing service

---

**Project Description**

**Project Repository**
https://github.com/BukinPK/sci

**Team Members and Contact info**
@Dene33 @BukinPK

**Comment by jakzilla** [comment]
Several people have mentioned the broken system of scientific publishing could be a good Colony use case! Good luck! 👍

**Comment by jrmoreau** [comment]
@BukinPK will you need anymore team members?

**Comment by BukinPK** [comment]
@jrmoreau, I think that not yet. Given the language barrier, this will create more difficulties for us than good.
But thanks for the suggestion.
