### ISSUE TITLE
HedgeAI - An AI powered opensource cryptocurrency hedge fund

### ISSUE THREAD

**Issue by vyomshm** [JoinColony/colonyHackathon#94]
### Colony Hackathon Submission

**Project Title**

HedgeAI - An AI powered opensource cryptocurrency hedge fund
---

**Project Description**

Primarily, HedgeAI will be a DAPP for a public cryptocurrency fund managed by a colony.
The fund will live entirely on the ethereum blockchain with anyone able to invest in it. The opensource nature of HedgeAI will allow public to easily track its performance statistics.
Investors who invest in HedgeAI would be issued a certain amount of HedgeAI's native colony token(ERC20) called HAI. 
The primary purpose of HedgeAI will be to make profitable investments regardless of the market trends but it will also serve as a platform for other individuals who wis to bootstrap their own crypt hedge funds.
Majority of investments for hedgeAI would be made via a secure trading-bot using intelligence from a crowdsourced-AI platform for data scientists/quants. 

**Project Repository**

https://github.com/vyomshm/HedgeAI

**Team Members and Contact info**

Vyom Sharma
twitter - @vcrizpy

**Comment by gichiba** [comment]
Cool idea! Would you be using tasks and reputation to allow individuals to influence behavior of the trading bot? 

Anyways, you can ask any questions about Colony or colonyJS in the Gitter, and I'll do my best to help answer them. Happy Hacking!

**Comment by jrmoreau** [comment]
@vyomshm do you need team members? I would urge you to post in Gitter for what you need skill-wise.
